// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5POwq7iI69CBFyDnZBBmj2Qx2gAyXc30',
    appId: '1:811582252942:android:17095fcf1cd8dd1229e6df',
    messagingSenderId: '811582252942',
    projectId: 'chatdemo-2eeeb',
    storageBucket: 'chatdemo-2eeeb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAX5AMVrfN0hBs68103cqyNkGpAz3ZKEA',
    appId: '1:811582252942:ios:be892e9445bd633529e6df',
    messagingSenderId: '811582252942',
    projectId: 'chatdemo-2eeeb',
    storageBucket: 'chatdemo-2eeeb.appspot.com',
    androidClientId: '811582252942-tcc0o01ieq96689494j5idejuo7ek6h4.apps.googleusercontent.com',
    iosClientId: '811582252942-2mnrc80b32u8qupgp1n2nkl8h2ngheu2.apps.googleusercontent.com',
    iosBundleId: 'com.mk.chatDemo',
  );
}
